### ISSUE TITLE
VTK view fails

### ISSUE THREAD

**Issue by poinot** [pyCGNS/pyCGNS#19]
Traceback (most recent call last):
File "D:\poinot\AppData\Local\Continuum\Anaconda\lib\site-packages\pycgns-4.6.561-py2.7-win-amd64.egg\CGNS\NAV\wfingerprint.py", line 358, in closeEvent
self.FG.closeView(self._index)
File "D:\poinot\AppData\Local\Continuum\Anaconda\lib\site-packages\pycgns-4.6.561-py2.7-win-amd64.egg\CGNS\NAV\wfingerprint.py", line 713, in closeView
vw.doRelease()
File "D:\poinot\AppData\Local\Continuum\Anaconda\lib\site-packages\pycgns-4.6.561-py2.7-win-amd64.egg\CGNS\NAV\wvtk.py", line 199, in doRelease
self.reject()
File "D:\poinot\AppData\Local\Continuum\Anaconda\lib\site-packages\pycgns-4.6.561-py2.7-win-amd64.egg\CGNS\NAV\wvtk.py", line 1154, in reject
if (self._master._vtkwindow is not None):
AttributeError: 'Q7VTK' object has no attribute '_master'

**Comment by MicK7** [comment]
Not reproducible issue on current master.
reject function code is now quite different.
