### ISSUE TITLE
[MAP] Inconsistence of CGNS.MAP.save signature VS doc

### ISSUE THREAD

**Issue by picost** [pyCGNS/pyCGNS#93]
A statement as `CGM.save('test_CGMsave.cgns', main_tree, [])` fails whereas the online doc gives the following signature:

`status=CGNS.MAP.save(filename,tree,links,flags,depth,linkpaths,updatepaths,skiplist)`

See test script attached which result is:
```
$ python test_CGMsave.py 
5.0.625
Traceback (most recent call last):
  File "test_CGMsave.py", line 14, in <module>
    CGM.save('test_CGMsave.cgns', main_tree, [])
  File "CGNS/MAP/EmbeddedCHLone.pyx", line 530, in CGNS.MAP.EmbeddedCHLone.save
TypeError: save() takes exactly 2 positional arguments (3 given)
```
[test_CGMsave.py.txt](https://github.com/pyCGNS/pyCGNS/files/3305315/test_CGMsave.py.txt)

Suggested fix: update the doc to explicitely state that all other arguments are non positional arguments and that passing them as kwargs is therefore mandatory.

**Comment by picost** [comment]
Didn't read the doc correctly apparently
